### PR TITLE
Timeline - after device rotation, changes of "show last" and "interval mode" will be not saved, it rolls back to default values

### PR DESCRIPTION
**Pull request by harigl**
https://trello.com/c/QIdlnhql/21-timeline-after-device-rotation-changes-of-show-last-and-interval-mode-will-be-not-saved-it-rolls-back-to-default-values

### CODE REVIEW

**Comment by murphyalexandre** [comment]
@harigl Can you show me a quick screen share of the fix?

**Comment by harigl** [comment]
https://user-images.githubusercontent.com/17403364/162150624-00ef9cd7-a069-43c4-810d-2c279311b2f3.mp4



> @harigl Can you show me a quick screen share of the fix?

**Comment by murphyalexandre** [comment]
> 124447-720x1560.mp4
> 
> > @harigl Can you show me a quick screen share of the fix?

Sorry to ask for more, but can you show the before too? Can't seem to understand what should be fixed!

**Comment by harigl** [comment]
https://user-images.githubusercontent.com/17403364/162435996-81b474d7-504a-4ce5-9a89-4a78e94919ab.mp4

Before fixing the issue

**Review by murphyalexandre — APPROVED** [review]

**Comment by harigl** [comment]
https://user-images.githubusercontent.com/17403364/162436541-22c10887-1ed0-4303-92ae-8d67795bb93b.mp4

after

**Pull request merged**
